-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN
    (SELECT MP.MEMBER_ID
    FROM MEMBER_PROFILE MP
    JOIN REST_REVIEW RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY MP.MEMBER_ID
    HAVING COUNT(MP.MEMBER_ID) =
        (SELECT COUNT(RR.MEMBER_ID)
        FROM MEMBER_PROFILE MP
        JOIN REST_REVIEW RR
        ON MP.MEMBER_ID = RR.MEMBER_ID
        GROUP BY MP.MEMBER_ID
        ORDER BY COUNT(MP.MEMBER_ID) DESC
        LIMIT 1
        )
    )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
;

