SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS row_num
    FROM FISH_INFO
) FI
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.row_num = 1
ORDER BY FI.ID ASC
;