-- 코드를 작성해주세요
SELECT FI2.ID, FNI.FISH_NAME, FI.LENGTH AS LENGTH
FROM (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) FI
JOIN FISH_INFO FI2
ON FI.LENGTH = FI2.LENGTH AND FI.FISH_TYPE = FI2.FISH_TYPE
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE;